### ISSUE TITLE
IBM 1130 GDU character rendering incorrect

### ISSUE THREAD

**Issue by pekka-28** [simh/simh#464]
I have tried to extend the gdu.asm sample to display text.

To do this, I have created a subset of the character tables using the sample typeface in one of the other IBM 2250 model hardware manuals.

The program runs and displays the small displacement vectors, but incorrectly.

- #### Context

In the coordinate mapping in the function draw_characters() in ibm1130_gdu.c, the following code is present:
            x1 = gdu_x + (int) (x1*ci->sx + 0.5);
            y1 = gdu_y + (int) ((y1+yoff)*ci->sy + 0.5);

This appears to be inconsistent with the scaling used earlier in the function as only the y-coordinate is offset. The horizontal lines appear to be correct, but lines with a vertical component are sheared.

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
IBM 1130 simulator V3.8-0 [32b data, 32b addresses, no Ethernet]

- #### how you built the simulator or that you're using prebuilt binaries
Prebuilt

- #### the simulator configuration file (or commands) which were used when the problem occurred.
default script for gdu.asm

- #### the expected behavior and the actual behavior
![image](https://cloud.githubusercontent.com/assets/4647573/26291071/1b841e32-3eac-11e7-88c2-722e7f4bf938.png)
[gdu.txt](https://github.com/simh/simh/files/1017622/gdu.txt)

Should display three triangles and a square (correct) and the string ':@a>><<2X' where '@' is a box with a cross through it. The text displays incorrectly.

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

I have previously reported this to Brian, but see that the error is still present.

**Comment by markpizz** [comment]
@pekka-28 please put your full name in your Github profile so folks reading and working on this can tell who you are.  Thanks.

simh V3.8-0 was released approximately 9 years ago.  This problem may have been fixed.  Please try the latest simulator code which is available in a pre-built Windows binary at:  https://github.com/simh/Win32-Development-Binaries

If the problem still exists, feel free to suggest changes to the code to fix the problem.

Meanwhile, your above: "default script for gdu.asm" doesn't help me to reproduce the problem.  Will you be more specific?

Thanks.

- Mark

**Comment by pekka-28** [comment]
The problems are still present. Graphical rendering still shows the same result.

The script was supplied as part of the emulator previously. I see that it is no longer part of the distribution. The content of the script and the job cards are appended.
--
del gdu.lst
att dsk dms.dsk
att prt gdu.lst
att cr @gdu.job
boot dsk
--
!// asm
!*list all
gdu.asm	a
!// xeq

**Comment by markpizz** [comment]
What is the output of SHOW VERSION with the latest simulator?

Do you have the ability to build an executable and test your proposed change?  That would be the easiest way to solve this.

**Comment by pekka-28** [comment]
Show version is updated in previous comment.

I don't have a compiler that I can use at present to generate the executable. I would have probably done so if I had the capability.

**Comment by markpizz** [comment]
A compiler which will work fine on your Windows 10 system can be had here:

http://download.microsoft.com/download/E/8/E/E8EEB394-7F42-4963-A2D8-29559B738298/VS2008ExpressWithSP1ENUX1504728.iso

Read "Visual Studio Projects\0ReadMe_Projects.txt" for details and open the "Visual Studio Projects\simh.sln" solution file.

**Comment by pekka-28** [comment]
Mark

I have Visual Studio installed on my machine, but there is currently a licensing mess with our MSDN agreement. I’d really prefer not to have to duplicate the installation and risk imploding the current configuration.

I understand that it is preferable to trial the changes before submitting a push back into the tree, but I am not able to perform this at the moment.

As I only infrequently look at the 1130 work in any event, I’m not really anxious to get the problem resolved any time soon. If you feel that I am causing too much trouble, feel free to close the issue as not required. I had thought that since the general quality of the tool was quite good, discovering multiple errors in what looks like a under used component would have been accepted and fitted into a backlog along with other defects.

Regards
Pekka Pihlajasaari
--
pekka@data.co.za           Data Abstraction (Pty) Ltd         +27 11 484 9664

**Comment by markpizz** [comment]
Pekka,

You can install MinGW and use that without messing with your Visual Studio configuration.  Debugging is harder, but the latest MinGW does work with the 1130 simulator.  You should be able to install that with: https://sourceforge.net/projects/mingw/files/Installer/mingw-get-setup.exe/download

I'm not an actual user of the 1130 simulator, so it isn't obvious to me how to reproduce and verify a problem, or know what to expect that might fix it.

- Mark

**Comment by pekka-28** [comment]
Mark

I’ll see if I can get a compiler working on my machine. Thanks for the assistance.

Regards
Pekka Pihlajasaari
--
pekka@data.co.za           Data Abstraction (Pty) Ltd         +27 11 484 9664
