### ISSUE TITLE
VMS on VAX at commit 44bfd68a randomly crashes - macOS 10.13

### ISSUE THREAD

**Issue by nickca** [simh/simh#595]
Running VMS 7.3 under commit 44bfd68a on macOS 10.13, it randomly crashes back to the sim> prompt. I rolled back to commit 8c0439fe (the last change I saw in the log to VAX) and it no longer occurs.

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
"Random crash back to sim> prompt" isn't much to go on.  There must, at least, be a message just before the sim> prompt is output.

Additionally, your configuration file would be helpful.

The output of "SHOW TERM" on the VH port you are using would help as well.

Since you're comfortable walking between different commits to point at the problem, please use "git bisect" to identify the specific change that actually introduced the problem. Start the bisect at 8c0439f ...

**Comment by nickca** [comment]
I was actually mistaken in my original post - it continued happening until
I rolled back to cc6140fd. I updated back to 44bfd68a which is apparently
the latest commit as of this writing and recompiled. I'm actually not
incredibly comfortable with git - I had to read a tutorial on how to get
back to a working version.

The message when it crashes (at least at the time I recompiled and recorded
it) is:
Invalid argument, PC: 80F7FF8D (BBC #3,26C(R3),80F7FFE1)

Here is my SHOW TERM:
SYS$SYSDEVICE:[USERS.NICKCA]$ show term
Terminal: _OPA0:      Device_Type: VT100         Owner: NICKCA

   Input:     300     LFfill:  0      Width: 111      Parity: None
   Output:    300     CRfill:  0      Page:   33

Terminal Characteristics:
   Interactive        Echo               Type_ahead         No Escape
   No Hostsync        TTsync             Lowercase          Tab
   Wrap               Scope              No Remote          No Eightbit
   No Broadcast       No Readsync        No Form            Fulldup
   No Modem           No Local_echo      No Autobaud        No Hangup
   No Brdcstmbx       No DMA             No Altypeahd       Set_speed
   No Commsync        Line Editing       Insert editing     No Fallback
   No Dialup          No Secure server   No Disconnect      No Pasthru
   No Syspassword     No SIXEL Graphics  No Soft Characters No Printer Port
   Numeric Keypad     ANSI_CRT           No Regis           No Block_mode
   Advanced_video     No Edit_mode       DEC_CRT            No DEC_CRT2
   No DEC_CRT3        No DEC_CRT4        No DEC_CRT5        No Ansi_Color

Here is my config file:
;CPU
SET CPU 64m
SET CPU IDLE=VMS
SET CPU MODEL=VAXstation
ATTACH NVR /usr/local/share/SIMH/nvram.bin
;Disks
;VMS 5.5-2
;SET RQ0 RA90
;VMS 7.3
SET RQ0 RA92
SET RQ1 RRD40
SET RQ2 RA81
SET RQ3 DISABLE
;VMS 5.5-2
;ATTACH RQ0 /usr/local/share/SIMH/VMS-RQ0.dsk
;ATTACH RQ1 /usr/local/share/SIMH/VMS552.iso
;VMS 7.3
ATTACH RQ0 /usr/local/share/SIMH/OVMS-73-ra92.dsk
;ATTACH RQ1 /usr/local/share/SIMH/ovms73vaxhkit.iso
;ATTACH RQ2 /usr/local/share/SIMH/vms-soft-ra81.dsk
;Tape
SET TQ TK50
SET TQ1 DISABLE
SET TQ2 DISABLE
SET TQ3 DISABLE
;DECtape
;SET TDC ENABLED
;SET TDC0 LOCKED
;Serial
SET DZ LINES=4
ATTACH -a DZ 2324
;Disabled devices
SET CR DISABLE
SET RL DISABLE
SET TS DISABLE
;Printer
ATTACH LPT /usr/local/share/SIMH/printer-output.txt
;Ethernet
SET XQ ENABLE
SET XQ TYPE=DELQA-T
SET XQ MAC=AA:00:04:00:C9:10
ATTACH XQ nat:network=
10.0.2.4/24,tcp=2323:10.0.2.4:23,tcp=2321:10.0.2.4:21,tcp=2322:10.0.2.4:22

;Boot
SET CPU CONHALT
DEP BDR 0
BOOT CPU

Output of "show version" at SIMH console:
sim> show version
VAXStation 3900 (KA655) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)
        Simulator Compiled as C arch: x64 (Release Build) on Jul 11 2018 at
00:06:16
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.8
        PCRE RegEx (Version 8.42 2018-03-20) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin users-MacBook 17.6.0 Darwin Kernel Version 17.6.0: Tue
May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
        git commit id: 44bfd68a
        git commit time: 2018-07-07T22:06:52-0700

**Comment by markpizz** [comment]
Well, I don't see the same problem you're seeing with the lasted code at all.  That 'invalid argument' could sometimes appear on versions more than a week back, but that problem was fixed before the commit you reporting about (44bfd68).  The changes in 44bfd68 now report an error which may have been ignored or otherwise not noticed previously.  This error message has some similar wording about invalid argument, but you don't land back at the sim> prompt, but the simulator's execution is aborted.  In any case, I've apparently fixed the error I saw the first time I enabled idling.  Please give the latest code a try.

Meanwhile, please put your full name in your GitHub profile.

Thanks.

**Comment by markpizz** [comment]
Please give the latest code a try.

Thanks.

**Comment by nickca** [comment]
Still crashes:
vax.ini-47> BOOT CPU

Invalid argument, PC: 80F7FF8D (BBC #3,26C(R3),80F7FFE1)

If it matters, every time this has happened that I can recall, I've been
running the Lynx browser.

**Comment by markpizz** [comment]
First: Nicholas, please put your full name on your GitHub profile.

Second: The test VAX/VMS system on my OS X environment has been running for 2 days without a problem.  Since you didn't provide the version details in your followup report I can't tell if you're running the code which should have fixed it.  Meanwhile, if you actually are running the latest code, I've just now added some better context reporting when errors like what you maybe be seeing occur.  Please pick up the latest code and give it a try and when it fails, please provide all the output produced ALONG with the output of SHOW VERSION from the sim> prompt.

Thanks.

- Mark

**Comment by nickca** [comment]
I don't know what has changed, but it's stopped happening. So this can be
closed, sorry if I led you on a wild goose chase.

SHOW VERSION:
MicroVAX 3900 simulator V4.0-0 Current        git commit id: 52e8c7f6
sim> show version
MicroVAX 3900 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        64b data
        64b addresses
        Threaded Ethernet Packet transports:PCAP:VDE:NAT:UDP
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)
        Simulator Compiled as C arch: x64 (Release Build) on Jul 21 2018 at
13:33:41
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: SDL Version 2.0.8
        PCRE RegEx (Version 8.42 2018-03-20) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin users-MacBook 17.6.0 Darwin Kernel Version 17.6.0: Tue
May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
        git commit id: 52e8c7f6
        git commit time: 2018-07-21T02:22:26-0700
